name: workflow03
on: [push]

jobs:
  jobs01:
    runs-on: ubuntu-latest
    steps:
        - name: step 01
          run: echo " check runs"
  jobs02:
    runs-on: ubuntu-latest
    steps:
        - name: unix commands
          run: |
            ls -lta
            pwd
      

