name: githubaction
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps: 
        - name: firstJob
          run: echo "The first Job"
        - name: multi-line-Jobs
          run: | 
            node -v
            npm -v
