name: workflow03
on: [push]

jobs:
  jobs01:
    runs-on: ubuntu-latest
    steps:
        - name: step01
          run: echo " check runs"
  jobs02:
    runs-on: ubuntu-latest
    needs: jobs01
    steps:
        - name: unix commands
          run: |
            ls -lta
            pwd
            echo $GIHUB_SHA
            echo $GIHUB_REPOSITORY
      

