name: Workflow01
on: [push]

jobs:
  run-shell-commands0:
    runs-on: ubuntu-latest
    needs: run-shell-commands1
    steps: 
        - name: firstJob
          run: echo "The first Job01"
        - name: multi-line-Jobs
          run: | 
            node -v
            npm -v

  run-shell-commands1:
    runs-on: ubuntu-latest
    steps: 
        - name: firstJob
          run: echo "The first Job"
        - name: multi-line-Jobs
          run: | 
            node -v
            npm -v
  run-shell-commands2:
    runs-on: ubuntu-latest
    needs: run-shell-commands1
    steps: 
        - name: firstJob
          run: echo "The first Job"
        - name: multi-line-Jobs
          run: | 
            node -v
            npm -v  
  run-shell-commands3:
    runs-on: ubuntu-latest
    needs: run-shell-commands1
    steps: 
        - name: firstJob
          run: echo "The first Job"
        - name: multi-line-Jobs
          run: | 
            node -v
            npm -v                
  run-shell-commands4:
    runs-on: ubuntu-latest
    needs: run-shell-commands3
    steps: 
        - name: firstJob
          run: echo "The first Job"
        - name: multi-line-Jobs
          run: | 
            node -v
            npm -v  
  run-shell-commands5:
    runs-on: ubuntu-latest
    needs: [run-shell-commands4, run-shell-commands3, run-shell-commands2, run-shell-commands0, run-shell-commands1]
    steps: 
        - name: firstJob
          run: echo "The first Job"
        - name: multi-line-Jobs
          run: | 
            node -v
            npm -v                          